use crate::*;

use winapi::um::d3d11shader::*;



/// \[[docs.microsoft.com](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_library_desc)\]
/// D3D11_SHADER_DESC
///
/// &amp;\[[u8]\] equivalent that's ABI-compatible with some D3D APIs
#[derive(Clone, Copy, Default)]
#[repr(C)] pub struct ShaderDesc<'s> {
    version:                        u32,
    creator:                        Option<CStrPtr<'s>>,
    flags:                          u32,
    constant_buffers:               u32,
    bound_resources:                u32,
    input_parameters:               u32,
    output_parameters:              u32,
    instruction_count:              u32,
    temp_register_count:            u32,
    temp_array_count:               u32,
    def_count:                      u32,
    dcl_count:                      u32,
    texture_normal_instructions:    u32,
    texture_load_instructions:      u32,
    texture_comp_instructions:      u32,
    texture_bias_instructions:      u32,
    texture_gradient_instructions:  u32,
    float_instruction_count:        u32,
    int_instruction_count:          u32,
    uint_instruction_count:         u32,
    static_flow_control_count:      u32,
    dynamic_flow_control_count:     u32,
    macro_instruction_count:        u32,
    array_instruction_count:        u32,
    cut_instruction_count:          u32,
    emit_instruction_count:         u32,
    gs_output_topology:             PrimitiveTopology,
    gs_max_output_vertex_count:     u32,
    input_primitive:                Primitive,
    patch_constant_parameters:      u32,
    gs_instance_count:              u32,
    control_points:                 u32,
    hs_output_primitive:            TessellatorOutputPrimitive,
    hs_partitioning:                TessellatorPartitioning,
    tessellator_domain:             TessellatorDomain,
    barrier_instructions:           u32,
    interlocked_instructions:       u32,
    texture_store_instructions:     u32,
}

test_layout! { ShaderDesc => unsafe D3D11_SHADER_DESC {
    version                         => Version,
    creator                         => Creator,
    flags                           => Flags,
    constant_buffers                => ConstantBuffers,
    bound_resources                 => BoundResources,
    input_parameters                => InputParameters,
    output_parameters               => OutputParameters,
    instruction_count               => InstructionCount,
    temp_register_count             => TempRegisterCount,
    temp_array_count                => TempArrayCount,
    def_count                       => DefCount,
    dcl_count                       => DclCount,
    texture_normal_instructions     => TextureNormalInstructions,
    texture_load_instructions       => TextureLoadInstructions,
    texture_comp_instructions       => TextureCompInstructions,
    texture_bias_instructions       => TextureBiasInstructions,
    texture_gradient_instructions   => TextureGradientInstructions,
    float_instruction_count         => FloatInstructionCount,
    int_instruction_count           => IntInstructionCount,
    uint_instruction_count          => UintInstructionCount,
    static_flow_control_count       => StaticFlowControlCount,
    dynamic_flow_control_count      => DynamicFlowControlCount,
    macro_instruction_count         => MacroInstructionCount,
    array_instruction_count         => ArrayInstructionCount,
    cut_instruction_count           => CutInstructionCount,
    emit_instruction_count          => EmitInstructionCount,
    gs_output_topology              => GSOutputTopology,
    gs_max_output_vertex_count      => GSMaxOutputVertexCount,
    input_primitive                 => InputPrimitive,
    patch_constant_parameters       => PatchConstantParameters,
    gs_instance_count               => cGSInstanceCount,
    control_points                  => cControlPoints,
    hs_output_primitive             => HSOutputPrimitive,
    hs_partitioning                 => HSPartitioning,
    tessellator_domain              => TessellatorDomain,
    barrier_instructions            => cBarrierInstructions,
    interlocked_instructions        => cInterlockedInstructions,
    texture_store_instructions      => cTextureStoreInstructions,
}}
