use std::io::Write;

use mmrbi::*;



pub fn update() {
    let _ = std::fs::create_dir("thindx/examples/screenshots");

    mmrbi::fs::write_if_modified_with("thindx/src/_examples.rs", |o|{
        writeln!(o, "// This file is autogenerated by _xtask.rs")?;
        writeln!(o)?;
        writeln!(o, "//! # Examples")?;
        writeln!(o, "use crate::*;")?;

        for e in mmrbi::fs::DirPathType::read_by_alphanumeric("thindx/examples").unwrap_or_else(|err| fatal!("unable to enumerate thindx/examples: {}", err)) {
            if !e.file_type.is_file() { continue }
            let name = e.path.file_name().unwrap_or_else(|| fatal!("expected file_name for {}", e.path.display()));
            let name = name.to_string_lossy();
            let name = match name.strip_suffix(".rs") { Some(n) => n, None => continue };

            let should_output_screenshot : bool;
            let should_output_text : bool;
            if name.starts_with("d3d9-") || name.starts_with("d3d11-") {
                should_output_screenshot = true;
                should_output_text = false;
            } else if name.starts_with("d3dcompiler-") {
                should_output_screenshot = false;
                should_output_text = true;
            } else {
                warning!("unknown prefix for example: {}", name);
                should_output_screenshot = false;
                should_output_text = false;
            }

            let out;
            if should_output_screenshot || should_output_text {
                let exe = format!(r"target\{config}\examples\{name}.exe", config="debug", name=name);
                status!("Running", "{}", exe);

                let mut cmd = Command::new(exe);
                cmd.current_dir("thindx");
                if should_output_screenshot {
                    cmd.env("THINDX_DOCS_EXAMPLE_SCREENSHOT_PATH", format!(r"examples\screenshots\{name}.png", name=name));
                }
                if should_output_text {
                    out = cmd.stdout0().unwrap_or_else(|err| fatal!("failed: {}", err));
                } else {
                    cmd.status0().unwrap_or_else(|err| fatal!("failed: {}", err));
                    out = String::new();
                }
            } else {
                out = String::new();
            }

            let src = std::fs::read_to_string(&e.path).unwrap_or_else(|err| fatal!("unable to read `{}`: {}", e.path.display(), err));
            let mut src = src.lines().peekable();

            writeln!(o)?;

            let mut any = false;
            while src.peek().map_or(false, |l| l.starts_with("//!")) {
                writeln!(o, "///{}", src.next().unwrap()[3..].trim_end())?;
                any = true;
            }
            if !any {
                writeln!(o, "/// {}", name)?;
            }

            while src.peek().map_or(false, |l| l.trim().is_empty()) { let _ = src.next(); }

            if should_output_screenshot {
                writeln!(o, "///")?;
                writeln!(o, "/// <center>")?;
                writeln!(o, "/// <h4 id=\"screenshots\" class=\"section-header\"><a href=\"#screenshots\">Screenshots</h4>")?;
                let path = format!("thindx/examples/screenshots/{name}.png", name=name);
                let url = if false {
                    format!("../../../../{}", path)
                } else {
                    format!("data:image/png;base64,{}", base64::encode(std::fs::read(path).unwrap()))
                };
                writeln!(o, "/// <img src=\"{}\">", url)?;
                writeln!(o, "/// </center>")?;
            }

            writeln!(o, "///")?;
            writeln!(o, "/// ### Source")?;
            writeln!(o, "/// ```no_run")?;
            for line in src {
                assert!(!line.contains("```"));
                writeln!(o, "/// {}", line.trim_end())?;
            }
            writeln!(o, "/// ```")?;

            if should_output_text || !out.is_empty() {
                writeln!(o, "///")?;
                writeln!(o, "/// ### Output")?;
                writeln!(o, "/// ```text")?;
                for line in out.lines() {
                    assert!(!line.contains("```"));
                    writeln!(o, "/// {}", line.trim_end())?;
                }
                writeln!(o, "/// ```")?;
            }
            writeln!(o, "///")?;
            writeln!(o, "/// ### To run this example yourself")?;
            writeln!(o, "/// ```cmd")?;
            writeln!(o, "/// git clone https://github.com/MaulingMonkey/thindx")?;
            writeln!(o, "/// cd thindx")?;
            writeln!(o, "/// cargo run --example {}", name)?;
            writeln!(o, "/// ```")?;
            writeln!(o, "pub const {} : () = ();", name.replace("-", "_"))?;
        }

        Ok(())
    }).unwrap_or_else(|err| fatal!("unable to create `thindx/src/_examples.rs`: {}", err));
}
