// This file is autogenerated by _xtask.rs

#![warn(rustdoc::broken_intra_doc_links)]

//! Rust ⮀ C++ coverage information based on Windows SDK 10.0.19041.0
//!
//! ⚠️ Scanned C++ definitions are not yet complete.
//! Based on [MaulingMonkey/windows-sdk-scanner](https://github.com/MaulingMonkey/windows-sdk-scanner).
//!
//! <style>#main { max-width: 1500px; }</style>
//!
//! # Headers
//!
//! | C++ Header | Interfaces | Structs | Enums |
//! | ---------- | ---------- | ------- | ----- |
//! | [unknwn.h](#unknwn) | ⚠️ 1 of 3 |   |   |
//! | [d3d11shader.h](#d3d11shader) | ✔️ 12 of 12 | ✔️ 9 of 9 | ✔️ 1 of 1 |
//! | [d3dcommon.h](#d3dcommon) | ⚠️ 2 of 3 | ✔️ 1 of 1 | ✔️ 22 of 22 |
//! | [d3dcompiler.h](#d3dcompiler) |   | ✔️ 1 of 1 | ✔️ 2 of 2 |
//! | [d3d11shadertracing.h](#d3d11shadertracing) | ❌ 0 of 2 | ❌ 0 of 11 | ❌ 0 of 3 |
//!
//! <h3 id="unknwn">unknwn.h</h3>
//!
//!
//! |  ?  | C++ Interface | Rust Type | Methods |
//! | --- | ------------- | --------- | ------- |
//! | ❌ | `AsyncIUnknown` | | ❌ 0 of 6 |
//! | ❌ | `IClassFactory` | | ❌ 0 of 2 |
//! | ✔️ | [`IUnknown`](https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nn-unknwn-iunknown) | [`Unknown`]<br> | ✔️ 3 of 3 |
//!
//! |  ?  | C++ Method    | Rust Method |
//! | --- | ------------- | ----------- |
//! | ❌ | `AsyncIUnknown::Begin_AddRef` | |
//! | ❌ | `AsyncIUnknown::Begin_QueryInterface` | |
//! | ❌ | `AsyncIUnknown::Begin_Release` | |
//! | ❌ | `AsyncIUnknown::Finish_AddRef` | |
//! | ❌ | `AsyncIUnknown::Finish_QueryInterface` | |
//! | ❌ | `AsyncIUnknown::Finish_Release` | |
//! | ❌ | `IClassFactory::CreateInstance` | |
//! | ❌ | `IClassFactory::LockServer` | |
//! | ✔️ | [`IUnknown::AddRef`](https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-addref) | [`mcom::Rc::clone`]<br> |
//! | ✔️ | [`IUnknown::QueryInterface`](https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-queryinterface(q)) | [`mcom::Rc::try_cast`]<br> |
//! | ✔️ | [`IUnknown::Release`](https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-release) | [`mcom::Rc::drop`]<br> |
//! <h3 id="d3d11shader">d3d11shader.h</h3>
//!
//!
//! |  ?  | C++ Interface | Rust Type | Methods |
//! | --- | ------------- | --------- | ------- |
//! | ✔️ | [`ID3D11FunctionLinkingGraph`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11functionlinkinggraph) | [`d3d11::FunctionLinkingGraph`]<br> | ✔️ 8 of 8 |
//! | ✔️ | [`ID3D11FunctionParameterReflection`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11functionparameterreflection) | [`d3d11::FunctionParameterReflection`]<br> | ✔️ 1 of 1 |
//! | ✔️ | [`ID3D11FunctionReflection`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11functionreflection) | [`d3d11::FunctionReflection`]<br> | ✔️ 7 of 7 |
//! | ✔️ | [`ID3D11LibraryReflection`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11libraryreflection) | [`d3d11::LibraryReflection`]<br> | ✔️ 2 of 2 |
//! | ✔️ | [`ID3D11Linker`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11linker) | [`d3d11::Linker`]<br> | ✔️ 3 of 3 |
//! | ✔️ | [`ID3D11LinkingNode`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11linkingnode) | [`d3d11::LinkingNode`]<br> | ✔️ 0 of 0 |
//! | ✔️ | [`ID3D11Module`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11module) | [`d3d11::Module`]<br> | ✔️ 1 of 1 |
//! | ✔️ | [`ID3D11ModuleInstance`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11moduleinstance) | [`d3d11::ModuleInstance`]<br> | ✔️ 10 of 10 |
//! | ✔️ | [`ID3D11ShaderReflection`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11shaderreflection) | [`d3d11::ShaderReflection`]<br> | ✔️ 19 of 19 |
//! | ✔️ | [`ID3D11ShaderReflectionConstantBuffer`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11shaderreflectionconstantbuffer) | [`d3d11::ShaderReflectionConstantBuffer`]<br> | ✔️ 3 of 3 |
//! | ✔️ | [`ID3D11ShaderReflectionType`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11shaderreflectiontype) | [`d3d11::ShaderReflectionType`]<br> | ✔️ 11 of 11 |
//! | ✔️ | [`ID3D11ShaderReflectionVariable`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nn-d3d11shader-id3d11shaderreflectionvariable) | [`d3d11::ShaderReflectionVariable`]<br> | ✔️ 4 of 4 |
//!
//! |  ?  | C++ Struct    | Rust Type |
//! | --- | ------------- | --------- |
//! | ✔️ | [`D3D11_FUNCTION_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_function_desc) | [`d3d11::FunctionDesc`]<br> |
//! | ✔️ | [`D3D11_LIBRARY_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_library_desc) | [`d3d11::LibraryDesc`]<br> |
//! | ✔️ | [`D3D11_PARAMETER_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_parameter_desc) | [`d3d11::ParameterDesc`]<br> |
//! | ✔️ | [`D3D11_SHADER_BUFFER_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_shader_buffer_desc) | [`d3d11::ShaderBufferDesc`]<br> |
//! | ✔️ | [`D3D11_SHADER_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_shader_desc) | [`d3d11::ShaderDesc`]<br> |
//! | ✔️ | [`D3D11_SHADER_INPUT_BIND_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_shader_input_bind_desc) | [`d3d11::ShaderInputBindDesc`]<br> |
//! | ✔️ | [`D3D11_SHADER_TYPE_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_shader_type_desc) | [`d3d11::ShaderTypeDesc`]<br> |
//! | ✔️ | [`D3D11_SHADER_VARIABLE_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_shader_variable_desc) | [`d3d11::ShaderVariableDesc`]<br> |
//! | ✔️ | [`D3D11_SIGNATURE_PARAMETER_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ns-d3d11shader-d3d11_signature_parameter_desc) | [`d3d11::SignatureParameterDesc`]<br> |
//!
//! |  ?  | C++ Enum      | Rust Type | Constants |
//! | --- | ------------- | --------- | --------- |
//! | ✔️ | [`D3D11_SHADER_VERSION_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/ne-d3d11shader-d3d11_shader_version_type) | [`d3d11::ShaderVersionType`]<br> | ??? of ??? |
//!
//! |  ?  | C++ Method    | Rust Method |
//! | --- | ------------- | ----------- |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::CallFunction`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-callfunction) | [`d3d11::FunctionLinkingGraph::call_function`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::CreateModuleInstance`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-createmoduleinstance) | [`d3d11::FunctionLinkingGraph::create_module_instance`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::GenerateHlsl`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-generatehlsl) | [`d3d11::FunctionLinkingGraph::generate_hlsl`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::GetLastError`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-getlasterror) | [`d3d11::FunctionLinkingGraph::get_last_error`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::PassValue`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-passvalue) | [`d3d11::FunctionLinkingGraph::pass_value`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::PassValueWithSwizzle`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-passvaluewithswizzle) | [`d3d11::FunctionLinkingGraph::pass_value_with_swizzle`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::SetInputSignature`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-setinputsignature) | [`d3d11::FunctionLinkingGraph::set_input_signature`]<br> |
//! | ✔️ | [`ID3D11FunctionLinkingGraph::SetOutputSignature`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionlinkinggraph-setoutputsignature) | [`d3d11::FunctionLinkingGraph::set_output_signature`]<br> |
//! | ✔️ | [`ID3D11FunctionParameterReflection::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionparameterreflection-getdesc) | [`d3d11::FunctionParameterReflection::get_desc`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetConstantBufferByIndex`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getconstantbufferbyindex) | [`d3d11::FunctionReflection::get_constant_buffer_by_index`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetConstantBufferByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getconstantbufferbyname) | [`d3d11::FunctionReflection::get_constant_buffer_by_name`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getdesc) | [`d3d11::FunctionReflection::get_desc`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetFunctionParameter`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getfunctionparameter) | [`d3d11::FunctionReflection::get_function_parameter`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetResourceBindingDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getresourcebindingdesc) | [`d3d11::FunctionReflection::get_resource_binding_desc`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetResourceBindingDescByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getresourcebindingdescbyname) | [`d3d11::FunctionReflection::get_resource_binding_desc_by_name`]<br> |
//! | ✔️ | [`ID3D11FunctionReflection::GetVariableByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11functionreflection-getvariablebyname) | [`d3d11::FunctionReflection::get_variable_by_name`]<br> |
//! | ✔️ | [`ID3D11LibraryReflection::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11libraryreflection-getdesc) | [`d3d11::LibraryReflection::get_desc`]<br> |
//! | ✔️ | [`ID3D11LibraryReflection::GetFunctionByIndex`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11libraryreflection-getfunctionbyindex) | [`d3d11::LibraryReflection::get_function_by_index`]<br> |
//! | ✔️ | [`ID3D11Linker::AddClipPlaneFromCBuffer`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11linker-addclipplanefromcbuffer) | [`d3d11::Linker::add_clip_plane_from_cbuffer`]<br> |
//! | ✔️ | [`ID3D11Linker::Link`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11linker-link) | [`d3d11::Linker::link`]<br> |
//! | ✔️ | [`ID3D11Linker::UseLibrary`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11linker-uselibrary) | [`d3d11::Linker::use_library`]<br> |
//! | ✔️ | [`ID3D11Module::CreateInstance`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11module-createinstance) | [`d3d11::Module::create_instance`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindConstantBuffer`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindconstantbuffer) | [`d3d11::ModuleInstance::bind_constant_buffer`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindConstantBufferByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindconstantbufferbyname) | [`d3d11::ModuleInstance::bind_constant_buffer_by_name`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindResource`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindresource) | [`d3d11::ModuleInstance::bind_resource`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindResourceAsUnorderedAccessView`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindresourceasunorderedaccessview) | [`d3d11::ModuleInstance::bind_resource_as_unordered_access_view`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindResourceAsUnorderedAccessViewByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindresourceasunorderedaccessviewbyname) | [`d3d11::ModuleInstance::bind_resource_as_unordered_access_view_by_name`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindResourceByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindresourcebyname) | [`d3d11::ModuleInstance::bind_resource_by_name`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindSampler`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindsampler) | [`d3d11::ModuleInstance::bind_sampler`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindSamplerByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindsamplerbyname) | [`d3d11::ModuleInstance::bind_sampler_by_name`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindUnorderedAccessView`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindunorderedaccessview) | [`d3d11::ModuleInstance::bind_unordered_access_view`]<br> |
//! | ✔️ | [`ID3D11ModuleInstance::BindUnorderedAccessViewByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11moduleinstance-bindunorderedaccessviewbyname) | [`d3d11::ModuleInstance::bind_unordered_access_view_by_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetBitwiseInstructionCount`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getbitwiseinstructioncount) | [`d3d11::ShaderReflection::get_bitwise_instruction_count`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetConstantBufferByIndex`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getconstantbufferbyindex) | [`d3d11::ShaderReflection::get_constant_buffer_by_index`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetConstantBufferByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getconstantbufferbyname) | [`d3d11::ShaderReflection::get_constant_buffer_by_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetConversionInstructionCount`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getconversioninstructioncount) | [`d3d11::ShaderReflection::get_conversion_instruction_count`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getdesc) | [`d3d11::ShaderReflection::get_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetGSInputPrimitive`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getgsinputprimitive) | [`d3d11::ShaderReflection::get_gs_input_primitive`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetInputParameterDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getinputparameterdesc) | [`d3d11::ShaderReflection::get_input_parameter_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetMinFeatureLevel`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getminfeaturelevel) | [`d3d11::ShaderReflection::get_min_feature_level`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetMovInstructionCount`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getmovinstructioncount) | [`d3d11::ShaderReflection::get_mov_instruction_count`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetMovcInstructionCount`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getmovcinstructioncount) | [`d3d11::ShaderReflection::get_movc_instruction_count`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetNumInterfaceSlots`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getnuminterfaceslots) | [`d3d11::ShaderReflection::get_num_interface_slots`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetOutputParameterDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getoutputparameterdesc) | [`d3d11::ShaderReflection::get_output_parameter_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetPatchConstantParameterDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getpatchconstantparameterdesc) | [`d3d11::ShaderReflection::get_patch_constant_parameter_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetRequiresFlags`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getrequiresflags) | [`d3d11::ShaderReflection::get_requires_flags`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetResourceBindingDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getresourcebindingdesc) | [`d3d11::ShaderReflection::get_resource_binding_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetResourceBindingDescByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getresourcebindingdescbyname) | [`d3d11::ShaderReflection::get_resource_binding_desc_by_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetThreadGroupSize`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getthreadgroupsize) | [`d3d11::ShaderReflection::get_thread_group_size`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::GetVariableByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-getvariablebyname) | [`d3d11::ShaderReflection::get_variable_by_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflection::IsSampleFrequencyShader`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflection-issamplefrequencyshader) | [`d3d11::ShaderReflection::is_sample_frequency_shader`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionConstantBuffer::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionconstantbuffer-getdesc) | [`d3d11::ShaderReflectionConstantBuffer::get_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionConstantBuffer::GetVariableByIndex`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionconstantbuffer-getvariablebyindex) | [`d3d11::ShaderReflectionConstantBuffer::get_variable_by_index`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionConstantBuffer::GetVariableByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionconstantbuffer-getvariablebyname) | [`d3d11::ShaderReflectionConstantBuffer::get_variable_by_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetBaseClass`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getbaseclass) | [`d3d11::ShaderReflectionType::get_base_class`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getdesc) | [`d3d11::ShaderReflectionType::get_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetInterfaceByIndex`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getinterfacebyindex) | [`d3d11::ShaderReflectionType::get_interface_by_index`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetMemberTypeByIndex`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getmembertypebyindex) | [`d3d11::ShaderReflectionType::get_member_type_by_index`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetMemberTypeByName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getmembertypebyname) | [`d3d11::ShaderReflectionType::get_member_type_by_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetMemberTypeName`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getmembertypename) | [`d3d11::ShaderReflectionType::get_member_type_name`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetNumInterfaces`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getnuminterfaces) | [`d3d11::ShaderReflectionType::get_num_interfaces`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::GetSubType`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-getsubtype) | [`d3d11::ShaderReflectionType::get_sub_type`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::ImplementsInterface`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-implementsinterface) | [`d3d11::ShaderReflectionType::implements_interface`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::IsEqual`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-isequal) | [`d3d11::ShaderReflectionType::is_equal`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionType::IsOfType`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectiontype-isoftype) | [`d3d11::ShaderReflectionType::is_of_type`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionVariable::GetBuffer`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionvariable-getbuffer) | [`d3d11::ShaderReflectionVariable::get_buffer`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionVariable::GetDesc`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionvariable-getdesc) | [`d3d11::ShaderReflectionVariable::get_desc`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionVariable::GetInterfaceSlot`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionvariable-getinterfaceslot) | [`d3d11::ShaderReflectionVariable::get_interface_slot`]<br> |
//! | ✔️ | [`ID3D11ShaderReflectionVariable::GetType`](https://docs.microsoft.com/en-us/windows/win32/api/d3d11shader/nf-d3d11shader-id3d11shaderreflectionvariable-gettype) | [`d3d11::ShaderReflectionVariable::get_type`]<br> |
//! <h3 id="d3dcommon">d3dcommon.h</h3>
//!
//!
//! |  ?  | C++ Interface | Rust Type | Methods |
//! | --- | ------------- | --------- | ------- |
//! | ✔️ | [`ID3D10Blob`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/nn-d3dcommon-id3d10blob) | [`d3d::BytesBlob`]<br> [`d3d::CodeBlob`]<br> [`d3d::ReadOnlyBlob`]<br> [`d3d::TextBlob`]<br> | ✔️ 2 of 2 |
//! | ❌ | `ID3DDestructionNotifier` | | ❌ 0 of 2 |
//! | ✔️ | [`ID3DInclude`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/nn-d3dcommon-id3dinclude) | [`d3d::AsInclude`]<br> | ❌ 0 of 2 |
//!
//! |  ?  | C++ Struct    | Rust Type |
//! | --- | ------------- | --------- |
//! | ✔️ | [`D3D_SHADER_MACRO`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ns-d3dcommon-d3d_shader_macro) | [`d3d::AsShaderMacros`]<br> |
//!
//! |  ?  | C++ Enum      | Rust Type | Constants |
//! | --- | ------------- | --------- | --------- |
//! | ✔️ | [`D3D_CBUFFER_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_cbuffer_type) | [`d3d::CBufferType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_DRIVER_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_driver_type) | [`d3d::DriverType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_FEATURE_LEVEL`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_feature_level) | [`d3d::FeatureLevel`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_INCLUDE_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_include_type) | [`d3d::IncludeType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_INTERPOLATION_MODE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_interpolation_mode) | [`d3d::InterpolationMode`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_MIN_PRECISION`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_min_precision) | [`d3d::MinPrecision`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_NAME`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_name) | [`d3d::Name`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_PARAMETER_FLAGS`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_parameter_flags) | [`d3d::ParameterFlags`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_PRIMITIVE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_primitive) | [`d3d::Primitive`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_PRIMITIVE_TOPOLOGY`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_primitive_topology) | [`d3d::PrimitiveTopology`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_REGISTER_COMPONENT_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_register_component_type) | [`d3d::RegisterComponentType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_RESOURCE_RETURN_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_resource_return_type) | [`d3d::ResourceReturnType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SHADER_CBUFFER_FLAGS`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_shader_cbuffer_flags) | [`d3d::ShaderCbufferFlags`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SHADER_INPUT_FLAGS`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_shader_input_flags) | [`d3d::ShaderInputFlags`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SHADER_INPUT_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_shader_input_type) | [`d3d::ShaderInputType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SHADER_VARIABLE_CLASS`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_shader_variable_class) | [`d3d::ShaderVariableClass`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SHADER_VARIABLE_FLAGS`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_shader_variable_flags) | [`d3d::ShaderVariableFlags`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SHADER_VARIABLE_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_shader_variable_type) | [`d3d::ShaderVariableType`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_SRV_DIMENSION`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_srv_dimension) | [`d3d::SrvDimension`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_TESSELLATOR_DOMAIN`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_tessellator_domain) | [`d3d::TessellatorDomain`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_TESSELLATOR_OUTPUT_PRIMITIVE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_tessellator_output_primitive) | [`d3d::TessellatorOutputPrimitive`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_TESSELLATOR_PARTITIONING`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/ne-d3dcommon-d3d_tessellator_partitioning) | [`d3d::TessellatorPartitioning`]<br> | ??? of ??? |
//!
//! |  ?  | C++ Method    | Rust Method |
//! | --- | ------------- | ----------- |
//! | ✔️ | [`ID3D10Blob::GetBufferPointer`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/nf-d3dcommon-id3d10blob-getbufferpointer) | [`d3d::BytesBlob::as_bytes`]<br> [`d3d::CodeBlob::as_bytes`]<br> [`d3d::CodeBlob::as_bytecode`]<br> [`d3d::ReadOnlyBlob::get_buffer`]<br> [`d3d::TextBlob::to_utf8`]<br> [`d3d::TextBlob::to_utf8_lossy`]<br> |
//! | ✔️ | [`ID3D10Blob::GetBufferSize`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcommon/nf-d3dcommon-id3d10blob-getbuffersize) | [`d3d::BytesBlob::len`]<br> [`d3d::CodeBlob::len`]<br> [`d3d::ReadOnlyBlob::get_buffer_size`]<br> |
//! | ❌ | `ID3DDestructionNotifier::RegisterDestructionCallback` | |
//! | ❌ | `ID3DDestructionNotifier::UnregisterDestructionCallback` | |
//! | ❌ | `ID3DInclude::Close` | |
//! | ❌ | `ID3DInclude::Open` | |
//! <h3 id="d3dcompiler">d3dcompiler.h</h3>
//!
//!
//! |  ?  | C++ Struct    | Rust Type |
//! | --- | ------------- | --------- |
//! | ✔️ | [`D3D_SHADER_DATA`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/ns-d3dcompiler-d3d_shader_data) | [`d3d::ShaderData`]<br> |
//!
//! |  ?  | C++ Enum      | Rust Type | Constants |
//! | --- | ------------- | --------- | --------- |
//! | ✔️ | [`D3DCOMPILER_STRIP_FLAGS`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/ne-d3dcompiler-d3dcompiler_strip_flags) | [`d3d::CompilerStripFlags`]<br> | ??? of ??? |
//! | ✔️ | [`D3D_BLOB_PART`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/ne-d3dcompiler-d3d_blob_part) | [`d3d::BlobPart`]<br> | ??? of ??? |
//! <h3 id="d3d11shadertracing">d3d11shadertracing.h</h3>
//!
//!
//! |  ?  | C++ Interface | Rust Type | Methods |
//! | --- | ------------- | --------- | ------- |
//! | ❌ | `ID3D11ShaderTrace` | | ❌ 0 of 8 |
//! | ❌ | `ID3D11ShaderTraceFactory` | | ❌ 0 of 1 |
//!
//! |  ?  | C++ Struct    | Rust Type |
//! | --- | ------------- | --------- |
//! | ❌ | `D3D11_COMPUTE_SHADER_TRACE_DESC` | |
//! | ❌ | `D3D11_DOMAIN_SHADER_TRACE_DESC` | |
//! | ❌ | `D3D11_GEOMETRY_SHADER_TRACE_DESC` | |
//! | ❌ | `D3D11_HULL_SHADER_TRACE_DESC` | |
//! | ❌ | `D3D11_PIXEL_SHADER_TRACE_DESC` | |
//! | ❌ | `D3D11_SHADER_TRACE_DESC` | |
//! | ❌ | `D3D11_TRACE_REGISTER` | |
//! | ❌ | `D3D11_TRACE_STATS` | |
//! | ❌ | `D3D11_TRACE_STEP` | |
//! | ❌ | `D3D11_TRACE_VALUE` | |
//! | ❌ | `D3D11_VERTEX_SHADER_TRACE_DESC` | |
//!
//! |  ?  | C++ Enum      | Rust Type | Constants |
//! | --- | ------------- | --------- | --------- |
//! | ❌ | `D3D11_SHADER_TYPE` | | ??? of ??? |
//! | ❌ | `D3D11_TRACE_GS_INPUT_PRIMITIVE` | | ??? of ??? |
//! | ❌ | `D3D11_TRACE_REGISTER_TYPE` | | ??? of ??? |
//!
//! |  ?  | C++ Method    | Rust Method |
//! | --- | ------------- | ----------- |
//! | ❌ | `ID3D11ShaderTrace::GetInitialRegisterContents` | |
//! | ❌ | `ID3D11ShaderTrace::GetReadRegister` | |
//! | ❌ | `ID3D11ShaderTrace::GetStep` | |
//! | ❌ | `ID3D11ShaderTrace::GetTraceStats` | |
//! | ❌ | `ID3D11ShaderTrace::GetWrittenRegister` | |
//! | ❌ | `ID3D11ShaderTrace::PSSelectStamp` | |
//! | ❌ | `ID3D11ShaderTrace::ResetTrace` | |
//! | ❌ | `ID3D11ShaderTrace::TraceReady` | |
//! | ❌ | `ID3D11ShaderTraceFactory::CreateShaderTrace` | |
use crate::*;
